/*INSERT TEST*/

INSERT INTO CS_User(USERNAME, MOTDEPASSE, VISIBILITY)
VALUES('admin', '$2a$10$FuPMKanOvLxrrEXGbzAM1u.r63nbZfUOY2ysjG7dnLMyLZDa2aUmK', '2');

INSERT INTO CS_TEXTE(EMPLACEMENT, CONTENU)
VALUES('acceuil', 'Bienvenue sur Catsa !');

INSERT INTO CS_TEXTE(EMPLACEMENT, CONTENU)
VALUES('contact', 'Contact');

INSERT INTO CS_TEXTE(EMPLACEMENT, CONTENU)
VALUES('presentation', 'Qui suis-je ?');

INSERT INTO CS_TYPE(NOM)
VALUES('Chambre');

INSERT INTO CS_TYPE(NOM)
VALUES('Commerce');

INSERT INTO CS_TYPE(NOM)
VALUES('Tableau');

INSERT INTO CS_CATEGORIE(NOM)
VALUES('Bibittes');

INSERT INTO CS_CATEGORIE(NOM)
VALUES('Mer');

INSERT INTO CS_CATEGORIE(NOM)
VALUES('Savane');